version: '2'
services:
  kaazing.example.com:
    build: dmz
    ports:
      - "8000:8000"
    hostname: "kaazing.example.com"
    environment:
      GATEWAY_OPTS: -Dfeature.http.proxy=true
  internal.example.com: 
    build: internal
    environment:
      GATEWAY_OPTS: -Dfeature.http.proxy=true
  rabbitmq:
    build: broker
